[package]
name = "rlconverter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5"
base64 = "0.21"

[[bin]]
name = "rlconverter"
path = "src/main.rs"
