[package]
name = "rlconverter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22.1"

[[bin]]
name = "rlconverter"
path = "src/main.rs"
